# █▀ ▀█▀ ▄▀█ █▀█ █▀ █░█ █ █▀█
# ▄█ ░█░ █▀█ █▀▄ ▄█ █▀█ █ █▀▀

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$line_break\
$character\
"""

palette = 'rose-pine'

[fill]
symbol = ' '
style = "bg:underlay"

[username]
format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:love"
style_user = "bg:overlay fg:iris"

[directory]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"
#"~" = ""

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)"
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
disabled = false
style = "bg:overlay"
format = '([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[✓](bg:overlay fg:iris)'
untracked = '[?](bg:overlay fg:gold)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!](bg:overlay fg:gold)'
renamed = '[»](bg:overlay fg:iris)'
deleted = '[×](style)'
staged = '[+](bg:overlay fg:gold)'
ahead = '[⇡](bg:overlay fg:foam)'
diverged = '⇕[\[](bg:overlay fg:iris)[⇡](bg:overlay fg:foam)[⇣](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[⇣)](bg:overlay fg:rose)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](fg:pine)'
error_symbol = '[❯](fg:love)'
vimcmd_symbol = '[❮](fg:pine)'
vimcmd_replace_one_symbol = '[❮](fg:iris)'
vimcmd_replace_symbol = '[❮](fg:iris)'
vimcmd_visual_symbol = '[❮](fg:gold)'

[palettes.rose-pine]
overlay = '#26233a'
underlay = '#191724'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

